import numpy     as np
import streamlit as st
# message = f1()
@st.cache_data(show_spinner="Spinning...")
def f1():
    n = np.random.randint(0, 100)
    message = "this is a message generated by a function"=str(n)
    
    if n>50:
        st.balloons()
    else:
        st.snow()
   
    return message