# -*- coding: utf-8 -*-
"""
Created on Wed May  8 16:32:37 2024

@author: marchenks
"""
import streamlit as st
# message = f1()
@st.cache_data(show_spinner="Spinning...")
def f1():
    message = "this is a message generated by a function"
        
    return message